/*
 * config.h - Generated by CMake from config.h.cmake
 * DO NOT EDIT! Change CMakeLists.txt configuration instead.
 */

/* Define if we have EBCDIC code */
#cmakedefine EBCDIC

/* Define unless no X support found */
#cmakedefine HAVE_X11

/* Define unless no Wayland support found */
#cmakedefine HAVE_WAYLAND

/* Define if you want focus stealing support with Wayland clipboard */
#cmakedefine FEAT_WAYLAND_CLIPBOARD_FS

/* Define when terminfo support found */
#cmakedefine TERMINFO

/* Define when termcap.h contains ospeed */
#cmakedefine HAVE_OSPEED

/* Define when ospeed can be extern */
#cmakedefine OSPEED_EXTERN

/* Define when termcap.h contains UP, BC and PC */
#cmakedefine HAVE_UP_BC_PC

/* Define when UP, BC and PC can be extern */
#cmakedefine UP_BC_PC_EXTERN

/* Define when termcap.h defines outfuntype */
#cmakedefine HAVE_OUTFUNTYPE

/* Define when del_curterm() is available */
#cmakedefine HAVE_DEL_CURTERM

/* Define when __DATE__ " " __TIME__ can be used */
#cmakedefine HAVE_DATE_TIME

/* Defined from $SOURCE_DATE_EPOCH, used as the build date */
#cmakedefine BUILD_DATE "@BUILD_DATE@"

/* Define when __attribute__((unused)) can be used */
#cmakedefine HAVE_ATTRIBUTE_UNUSED

/* defined always when using configure / CMake */
/* UNIX is defined via compile_definitions */

/* Defined to the size of an int */
#define MNV_SIZEOF_INT @MNV_SIZEOF_INT@

/* Defined to the size of a long */
#define MNV_SIZEOF_LONG @MNV_SIZEOF_LONG@

/* Defined to the size of off_t */
#define SIZEOF_OFF_T @SIZEOF_OFF_T@

/* Defined to the size of time_t */
#define SIZEOF_TIME_T @SIZEOF_TIME_T@

/* Define when wchar_t is only 2 bytes */
#cmakedefine SMALL_WCHAR_T

/* Memory move/copy selection */
#cmakedefine USEBCOPY
#cmakedefine USEMEMMOVE
#cmakedefine USEMEMCPY

/* Define when "man -s 2" is to be used */
#cmakedefine USEMAN_S

/* Feature defines */
/* HAVE_CONFIG_H is defined via compile_definitions */

/* Type sizes and properties */
#cmakedefine const
#cmakedefine volatile
#cmakedefine mode_t @mode_t@
#cmakedefine off_t @off_t@
#cmakedefine pid_t @pid_t@
#cmakedefine size_t @size_t@
#cmakedefine uid_t @uid_t@
#cmakedefine uint32_t @uint32_t@

/* Header file availability */
#cmakedefine HAVE_STDINT_H
#cmakedefine HAVE_STDLIB_H
#cmakedefine HAVE_STRING_H
#cmakedefine HAVE_STRINGS_H
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_SYS_WAIT_H
#cmakedefine HAVE_SYS_STAT_H
#cmakedefine HAVE_SYS_TYPES_H
#cmakedefine HAVE_SYS_UTSNAME_H
#cmakedefine HAVE_TERMIOS_H
#cmakedefine HAVE_TERMIO_H
#cmakedefine HAVE_SGTTY_H
#cmakedefine HAVE_SYS_IOCTL_H
#cmakedefine HAVE_SYS_TIME_H
#cmakedefine HAVE_SYS_SYSCTL_H
#cmakedefine HAVE_SYS_SYSINFO_H
#cmakedefine HAVE_SYS_SYSTEMINFO_H
#cmakedefine HAVE_SYS_STREAM_H
#cmakedefine HAVE_SYS_PTEM_H
#cmakedefine HAVE_SYS_RESOURCE_H
#cmakedefine HAVE_SYS_SELECT_H
#cmakedefine HAVE_SYS_UTIME_H
#cmakedefine HAVE_SYS_ACL_H
#cmakedefine HAVE_SYS_ACCESS_H
#cmakedefine HAVE_SYS_SYSCTL_H
#cmakedefine HAVE_SYS_PARAM_H
#cmakedefine HAVE_LOCALE_H
#cmakedefine HAVE_LIBGEN_H
#cmakedefine HAVE_WCHAR_H
#cmakedefine HAVE_WCTYPE_H
#cmakedefine HAVE_FLOAT_H
#cmakedefine HAVE_MATH_H
#cmakedefine HAVE_DIRENT_H
#cmakedefine HAVE_STROPTS_H
#cmakedefine HAVE_FCNTL_H
#cmakedefine HAVE_PWD_H
#cmakedefine HAVE_GRP_H
#cmakedefine HAVE_LANGINFO_H
#cmakedefine HAVE_LIBINTL_H
#cmakedefine HAVE_ERRNO_H
#cmakedefine HAVE_ICONV_H
#cmakedefine HAVE_INTTYPES_H
#cmakedefine HAVE_POLL_H
#cmakedefine HAVE_DLFCN_H
#cmakedefine HAVE_SETJMP_H
#cmakedefine HAVE_PTHREAD_H
#cmakedefine HAVE_PTHREAD_NP_H
#cmakedefine HAVE_UTIME_H
#cmakedefine HAVE_SYS_MMAN_H

/* Terminal library */
#cmakedefine HAVE_TGETENT
#cmakedefine HAVE_TERMCAP_H
#cmakedefine HAVE_TERM_H
#cmakedefine HAVE_CURSES_H
#cmakedefine HAVE_NCURSES_H
#cmakedefine HAVE_NCURSES_NCURSES_H
#cmakedefine HAVE_NCURSES_TERM_H

/* Function availability */
#cmakedefine HAVE_BCMP
#cmakedefine HAVE_BCOPY
#cmakedefine HAVE_FCHDIR
#cmakedefine HAVE_FCHOWN
#cmakedefine HAVE_FCHMOD
#cmakedefine HAVE_FSYNC
#cmakedefine HAVE_FDATASYNC
#cmakedefine HAVE_FSEEKO
#cmakedefine HAVE_FTRUNCATE
#cmakedefine HAVE_GETCWD
#cmakedefine HAVE_GETPWENT
#cmakedefine HAVE_GETPWNAM
#cmakedefine HAVE_GETPWUID
#cmakedefine HAVE_GETRLIMIT
#cmakedefine HAVE_GETTIMEOFDAY
#cmakedefine HAVE_GETWD
#cmakedefine HAVE_ICONV
#cmakedefine HAVE_LSTAT
#cmakedefine HAVE_MEMCMP
#cmakedefine HAVE_MEMSET
#cmakedefine HAVE_MKDTEMP
#cmakedefine HAVE_NANOSLEEP
#cmakedefine HAVE_OPENDIR
#cmakedefine HAVE_POSIX_OPENPT
#cmakedefine HAVE_PUTENV
#cmakedefine HAVE_QSORT
#cmakedefine HAVE_READLINK
#cmakedefine HAVE_REALPATH
#cmakedefine HAVE_RENAME
#cmakedefine HAVE_SELECT
#cmakedefine HAVE_SETENV
#cmakedefine HAVE_SETJMP_H
#cmakedefine HAVE_SETPGID
#cmakedefine HAVE_SETSID
#cmakedefine HAVE_SIGACTION
#cmakedefine HAVE_SIGALTSTACK
#cmakedefine HAVE_SIGCONTEXT
#cmakedefine HAVE_SIGSET
#cmakedefine HAVE_SIGSETJMP
#cmakedefine HAVE_SIGSTACK
#cmakedefine HAVE_SIGVEC
#cmakedefine HAVE_STRERROR
#cmakedefine HAVE_STRFTIME
#cmakedefine HAVE_STRICMP
#cmakedefine HAVE_STRNCASECMP
#cmakedefine HAVE_STRCASECMP
#cmakedefine HAVE_STRPBRK
#cmakedefine HAVE_STRTOL
#cmakedefine HAVE_ST_BLKSIZE
#cmakedefine HAVE_SYSCONF
#cmakedefine HAVE_SYSCTL
#cmakedefine HAVE_SYSINFO
#cmakedefine HAVE_TOWLOWER
#cmakedefine HAVE_TOWUPPER
#cmakedefine HAVE_ISWUPPER
#cmakedefine HAVE_USLEEP
#cmakedefine HAVE_UTIME
#cmakedefine HAVE_UTIMES
#cmakedefine HAVE_BIND_TEXTDOMAIN_CODESET
#cmakedefine HAVE_PANGO_SHAPE_FULL
#cmakedefine HAVE_TIMER_CREATE

/* Dynamic loading */
#cmakedefine HAVE_DLOPEN
#cmakedefine HAVE_DLSYM

/* Misc defines */
#cmakedefine HAVE_PATHDEF
#define HAVE_PATHDEF

/* Socket / channel support */
#cmakedefine HAVE_SOCKADDR_UN

/* Feature level */
#cmakedefine FEAT_HUGE
#cmakedefine FEAT_NORMAL
#cmakedefine FEAT_TINY

/* Optional features - set by CMake, consumed by feature.h */
#cmakedefine FEAT_NETBEANS_INTG
#cmakedefine FEAT_JOB_CHANNEL
#cmakedefine FEAT_TERMINAL
#cmakedefine FEAT_SOUND
#cmakedefine HAVE_CANBERRA
#cmakedefine FEAT_CSCOPE
#cmakedefine FEAT_EVAL
#cmakedefine FEAT_BEVAL
#cmakedefine FEAT_XIM
#cmakedefine FEAT_XSMP
#cmakedefine FEAT_CLIENTSERVER
#cmakedefine FEAT_CLIPBOARD
#cmakedefine FEAT_MOUSE_GPM
#cmakedefine FEAT_GUI
#cmakedefine FEAT_GUI_GTK
#cmakedefine USE_GTK3
#cmakedefine FEAT_GUI_MOTIF
#cmakedefine FEAT_GUI_X11
#cmakedefine FEAT_WAYLAND
#cmakedefine FEAT_WAYLAND_CLIPBOARD
#cmakedefine FEAT_IPV6
#cmakedefine WANT_SOCKETSERVER

/* Interpreter support */
#cmakedefine FEAT_LUA
#cmakedefine DYNAMIC_LUA
#cmakedefine FEAT_PERL
#cmakedefine DYNAMIC_PERL
#cmakedefine FEAT_PYTHON3
#cmakedefine DYNAMIC_PYTHON3
#cmakedefine FEAT_RUBY
#cmakedefine DYNAMIC_RUBY
#cmakedefine FEAT_TCL
#cmakedefine DYNAMIC_TCL
#cmakedefine FEAT_MZSCHEME
#cmakedefine DYNAMIC_MZSCHEME

/* Encryption */
#cmakedefine HAVE_SODIUM

/* select() argument types */
#ifndef SELECT_TYPE_ARG1
# define SELECT_TYPE_ARG1
#endif
#ifndef SELECT_TYPE_ARG234
# define SELECT_TYPE_ARG234 (fd_set *)
#endif
#ifndef SELECT_TYPE_ARG5
# define SELECT_TYPE_ARG5 (struct timeval *)
#endif
