/* pathdef.c - Generated by CMake
 * DO NOT EDIT! Change CMakeLists.txt configuration instead. */
#include "mnv.h"
char_u *default_mnv_dir = (char_u *)"@MNV_INSTALL_RCLOC@";
char_u *default_mnvruntime_dir = (char_u *)"@MNV_INSTALL_RTLOC@";
char_u *all_cflags = (char_u *)"@MNV_ALL_CFLAGS@";
char_u *all_lflags = (char_u *)"@MNV_ALL_LFLAGS@";
char_u *compiled_user = (char_u *)"@MNV_COMPILED_USER@";
char_u *compiled_sys = (char_u *)"@MNV_COMPILED_SYS@";
