name: "json4cpp: Publish documentation"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  publish_documentation:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: Project-Tick-Infrastructure/checkout@v2

      - name: Install virtual environment
        working-directory: json4cpp
        run: make install_venv -C docs/mkdocs

      - name: Build documentation
        working-directory: json4cpp
        run: make build -C docs/mkdocs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./json4cpp/docs/mkdocs/site
