name: Merge command

on:
  issue_comment:
    types: [created]

jobs:
  merge:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/merge') }}
    runs-on: ubuntu-latest
    steps:
      - uses: project-tick/project-tick/infra/merge-action@200b926eed82522c1fd033e2e4be9154b465438c
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          ssh_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
