name: Merge command

on:
  issue_comment:
    types: [created]

jobs:
  merge:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/merge') }}
    runs-on: ubuntu-latest
    steps:
      - uses: project-tick/project-tick/infra/merge-action@5994885f887ab8e0f9b06f9e6034407f984fb8ea
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          ssh_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
