name: "mnv: Check Links"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --config mnv/ci/lychee.toml mnv/
